### ISSUE TITLE
Typo and wrong charts in plot_time_function.py

### ISSUE THREAD

**Issue by MarcosCarreira** [X-DataInitiative/tick#452]
The last loop:

for tf, ax in zip(time_functions, ax_list):
    plot_timefunction(**tf_1,** ax=ax)
    ax.set_ylim([-0.5, 6.0])
plt.show()

Should be:

for tf, ax in zip(time_functions, ax_list):
    plot_timefunction(**tf**, ax=ax)
    ax.set_ylim([-0.5, 6.0])
plt.show()

And now the charts will be different (now they're all the same).

**Comment by Dekken** [comment]
PRs are welcome @MarcosCarreira

**Comment by Dekken** [comment]
I believe this has been resolved

**Comment by MarcosCarreira** [comment]
Yes, the PR was accepted. [https://github.com/X-DataInitiative/tick/blob/master/doc/modules/code_samples/plot_time_function.py](url) is Ok now but [https://x-datainitiative.github.io/tick/auto_examples/plot_time_function.html](url) still shows the old version.

**Comment by Dekken** [comment]
ok we have to regenerate the documentation, thanks @MarcosCarreira
